version: '3.8'

services:
  backend:
    build:
      context: ./Backend/RafaelChicovisBlog
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "4500:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=[CONNECTION_STRING]
      - Supabase__SupabaseUrl=[SUPABASE_URL]
      - Supabase__SupabaseKey=[SUPABASE_KEY]
      - Authentication__Audience=authenticated
      - Authentication__Issuer=[SUPABASE_URL]/auth/v1
      - Authentication__Authority=[SUPABASE_URL]/auth/v1
      - Authentication__Key=[SUPABASE_AUTH_KEY]
    networks:
      - app-network


  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8080:4000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
